# /etc/wireguard/wg0.conf
# umask 077
# wg genkey | tee /etc/wireguard/server_private.key | wg pubkey > /etc/wireguard/server_public.key
# wg genpsk > /etc/wireguard/psk.key
# Don't forget enable wg-quick@wg0; chmod 600 and ufw rules
[Interface]
Address = 10.66.66.1/24
ListenPort = 51820
PrivateKey = <PRIVATE KEY>

# Firewall rules: only allow forwarding through tunnel
PostUp = iptables -A FORWARD -i wg0 -o wg0 -j ACCEPT
PostDown = iptables -D FORWARD -i wg0 -o wg0 -j ACCEPT

[Peer]
# Client
PublicKey = <PUBLIC KEY>
PresharedKey = <PRESHARED KEY>
AllowedIPs = 10.66.66.2/32
